inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml

GitHub/RailsControllerRenderLiteral:
  Exclude:
    - app/controllers/**/*

GitHub/RailsControllerRenderPathsExist:
  Exclude:
    - app/controllers/**/*

