version: '3'
services:
  db:
    image: 'postgres:11.16'
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
  redis:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

volumes:
  pg-data:
  redis-data:
