version: '3'
services:
  db:
    image: "postgres:11.4"
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
  web:
    env_file:
      - .env.docker
    build: ./
    command: bash -c 'rm -f /usr/src/app/tmp/pids/server.pid; ./bin/dev'
    volumes:
      - ./:/usr/src/app:cached
      - tmp:/usr/src/app/tmp
      - gems:/usr/local/bundle
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379
    ports:
      - ${PORT}:3000
      # You may need to run `env $(cat .env.docker)` inline before docker-compose to set the right port

volumes:
  pg-data:
  redis-data:
  tmp:
  gems:
  node_modules: