name: Admin feature request
about: got a small feature for Ops or admins? let us hear you out
title: "Admin: [feature name here]"
labels: ''
body:
  - type: markdown
    id: problem
    attributes:
      label: Describe the problem
      description: What problem would this feature request solve?
      placeholder: Ex. I wish I could see the total amount of money raised by hackathon orgs in 2023.
    validations:
      required: true
