name: Admin feature request
description: got a small feature for Ops or admins? let us hear you out
title: "Admin: [feature name here]"
labels: []
body:
  - type: markdown
    value: |
      > [!TIP]
      > This is a great place for submitting Operations or admin-related feature requests! If you have a feature request for user/public-facing features, please reach out to @garyhtou
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      description: What problem would this feature request solve?
      placeholder: Ex. I wish I could see the total amount of money raised by hackathon orgs in 2023.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the feature/solution (optional)
      description: What solution or feature do you have in mind for solving your problem?
