# Name of your application. Used to uniquely configure containers.
service: bank

# Name of the container image.
image: hackclub/bank

# Deploy to these servers.
servers:
  web:
    - web.hcb.gg
  atm1:
    traefik: true
    hosts:
      - atm1.hcb.gg
  atm2:
    traefik: true
    hosts:
      - atm2.hcb.gg
  atm3:
    traefik: true
    hosts:
      - atm3.hcb.gg

# Credentials for your image host.
registry:
  server: ghcr.io
  username:
    - MRSK_REGISTRY_USERNAME
  password:
    - MRSK_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
env:
  clear:
    REDIS_URL: redis://167.235.200.107:6379
    DATABASE_URL: postgres://postgres:postgres@167.235.200.107:5432

# Call a broadcast command on deploys.
# audit_broadcast_cmd:
#   bin/broadcast

# Use a different ssh user than root
# ssh:
#   user: app

# Configure builder setup.
builder:
  remote:
    arch: amd64
    host: ssh://root@warehouse.hcb.gg

# Use accessory services (secrets come from .env).
accessories:
  db:
    image: postgres:11.16
    host: 167.235.200.107
    port: 5432
    env:
      clear:
        POSTGRES_PASSWORD: postgres
    directories:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    host: 167.235.200.107
    port: 6379
    directories:
      - redis-data:/data

# Configure custom arguments for Traefik
# traefik:
#   args:
#     accesslog: true
#     accesslog.format: json

# Configure a custom healthcheck (default is /up on port 3000)
healthcheck:
  path: /robots.txt
# port: 3000
