# Deploy to these servers.
servers:
  web:
    - atms.hcb.gg

labels:
  traefik.http.routers.bank.rule: HostSNI(`atm1.teleport.hcb.gg`)

# Inject ENV variables into containers (secrets come from .env).
env:
  clear:
    REDIS_URL: redis://atms.hcb.gg:6379
    DATABASE_URL: postgres://postgres:postgres@atms.hcb.gg:5432
