g_suite_mark_verifieds_job:
  cron: "*/5 * * * *" # run every 5 minutes
  class: "GSuiteJob::MarkVerifieds"
  queue: "default"
  
raw_plaid_transaction_imports_job:
  cron: "0 * * * *" # run every 1 hour
  class: "RawPlaidTransactionJob::Imports"
  queue: "default"

hashed_transaction_imports_job:
  cron: "10 * * * *" # run every 1 hour - at minute 10 (to space things out behind the plaid transaction import job)
  class: "HashedTransactionJob::Imports"
  queue: "default"
