g_suite_mark_verifieds_job:
  cron: "*/5 * * * *" # run every 5 minutes
  class: "GSuiteJob::MarkVerifieds"
  queue: "default"
  
pending_transaction_engine_nightly_job:
  cron: "*/30 * * * *" # run every 30 minutes
  class: "PendingTransactionEngineJob::Nightly"
  queue: "default"

pending_event_mapping_engine_nightly_job:
  cron: "*/35 * * * *" # run at every 35 minutes
  class: "PendingEventMappingEngineJob::Nightly"
  queue: "default"
 
transaction_engine_nightly_job:
  cron: "0 6 * * *" # run at 6am UTC each morning
  class: "TransactionEngineJob::Nightly"
  queue: "default"
  
event_mapping_engine_nightly_job:
  cron: "0 7 * * *" # run at 7am UTC each morning
  class: "EventMappingEngineJob::Nightly"
  queue: "default"

sync_payouts_job:
  cron: "0/30 * * * *" # run every 30 minutes
  class: "SyncPayoutsJob"
  queue: "default"

sync_emburse_cards_job:
  cron: "0 0 * * *" # run every 1 day
  class: "SyncEmburseCardsJob"
  queue: "default"

sync_emburse_transactions_job:
  cron: "0 0 * * *" # run every 1 day
  class: "SyncEmburseTransactionsJob"
  queue: "default"

sync_invoices_job:
  cron: "*/30 * * * *" # run every 30 minutes
  class: "SyncInvoicesJob"
  queue: "default"

sync_transactions_job:
  cron: "0 */2 * * *" # run every 2 hours
  class: "SyncTransactionsJob"
  queue: "default"

temp_job_fix_stripe_authorizations_nightly:
  cron: "0 0 1 9 *" # run september 1st
  class: "TempJob::FixStripeAuthorizationsNightly"
  queue: "default"

fee_reimbursement_nightly_job:
  cron: "0 0 * * *" # run every 1 day
  class: "FeeReimbursementJob::Nightly"
  queue: "default"

fee_nightly_job:
  cron: "0 0 1 * *" # run first day of each month
  class: "FeeJob::Monthly"
  queue: "default"
