g_suite_mark_verifieds_job:
  cron: "*/5 * * * *" # run every 5 minutes
  class: "GSuiteJob::MarkVerifieds"
  queue: "default"
  
plaid_transaction_imports_job:
  cron: "0 * * * *" # run every 1 hour
  class: "PlaidTransactionJob::Imports"
  queue: "default"