g_suite_mark_verifieds_job:
  cron: "*/5 * * * *" # run every 5 minutes
  class: "GSuiteJob::MarkVerifieds"
  queue: "default"
  
pending_transaction_engine_nightly_job:
  cron: "*/30 * * * *" # run every 30 minutes
  class: "PendingTransactionEngineJob::Nightly"
  queue: "default"

pending_event_mapping_engine_nightly_job:
  cron: "*/35 * * * *" # run at every 35 minutes
  class: "PendingEventMappingEngineJob::Nightly"
  queue: "default"
 
transaction_engine_nightly_job:
  cron: "0 6 * * *" # run at 6am UTC each morning
  class: "TransactionEngineJob::Nightly"
  queue: "default"

transaction_engine_friendly_memo_nightly_job:
  cron: "0 8 * * *" # run at 6am UTC each morning
  class: "TransactionEngineJob::FriendlyMemo::Nightly"
  queue: "default"
  
event_mapping_engine_nightly_job:
  cron: "0 7 * * *" # run at 7am UTC each morning
  class: "EventMappingEngineJob::Nightly"
  queue: "default"

sync_payouts_job:
  cron: "0/30 * * * *" # run every 30 minutes
  class: "SyncPayoutsJob"
  queue: "default"

sync_emburse_cards_job:
  cron: "0 0 * * *" # run every 1 day
  class: "SyncEmburseCardsJob"
  queue: "default"

sync_emburse_transactions_job:
  cron: "0 0 * * *" # run every 1 day
  class: "SyncEmburseTransactionsJob"
  queue: "default"

sync_transactions_job:
  cron: "0 */6 * * *" # run every 6 hours
  class: "SyncTransactionsJob"
  queue: "default"

fee_reimbursement_nightly_job:
  cron: "0 0 * * *" # run every 1 day
  class: "FeeReimbursementJob::Nightly"
  queue: "default"

fee_monthly_job:
  cron: "0 0 1 * *" # run first day of each month
  class: "FeeJob::Monthly"
  queue: "default"

disbursement_nightly_job:
  cron: "0 0 * * *" # run every 1 day
  class: "DisbursementJob::Nightly"
  queue: "default"

ach_transfer_nightly_job:
  cron: "*/30 * * * *" # run every 30 minutes
  class: "AchTransferJob::Nightly"
  queue: "default"

check_nightly_job:
  cron: "*/30 0 * * *" # run every 30 minutes
  class: "CheckJob::Nightly"
  queue: "default"

check_lob_url_assign_having_lob_id_job:
  cron: "0 0 * * *" # run every 1 day
  class: "CheckJob::LobUrl::AssignHavingLobId"
  queue: "default"

invoice_nightly_job:
  cron: "*/30 * * * *" # run every 30 minutes
  class: "InvoiceJob::Nightly"
  queue: "default"

donation_nightly_job:
  cron: "*/30 * * * *" # run every 30 minutes
  class: "DonationJob::Nightly"
  queue: "default"

payout_nightly_job:
  cron: "0 0 * * *" # run every 1 day
  class: "PayoutJob::Nightly"
  queue: "default"

fee_engine_hourly_job:
  cron: "0 */1 * * *" # run every 1 hours
  class: "FeeEngineJob::Hourly"
  queue: "default"

temp_job_sync_donations_aasm:
  cron: "0 0 * * *" # run every 1 day
  class: "TempJob::SyncDonationsAasm"
  queue: "default"

temp_job_sync_receipts_nightly:
  cron: "0 0 * * *" # run every 1 day
  class: "TempJob::SyncReceiptsNightly"
  queue: "default"

temp_job_sync_comments_nightly:
  cron: "0 0 * * *" # run every 1 day
  class: "TempJob::SyncCommentsNightly"
  queue: "default"

temp_job_sync_custom_memos_nightly:
  cron: "0 0 * * *" # run every 1 day
  class: "TempJob::SyncCustomMemosNightly"
  queue: "default"
