name: Handle PR Comment (Process Command)
on:
  issue_comment:
    types: [created]
jobs:
  process:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Process potential command
        uses: github/branch-deploy@v4.6.1
        id: branch-deploy
        with:
          trigger: .deploy
          environment: production
          environment_targets: production, atm1, atm2, atm3
          skip_ci: atm1, atm2, atm3
          skip_reviews: atm1, atm2, atm3
          environment_urls: production|https://web.hcb.gg, atm1|https://atm1.teleport.hcb.gg, atm2|https://atm2.teleport.hcb.gg, atm3|https://atm3.teleport.hcb.gg

      - name: Checkout code
        if: ${{ steps.branch-deploy.outputs.continue == 'true' }}
        uses: actions/checkout@v3.1.0
        with:
          ref: ${{ steps.branch-deploy.outputs.ref }}

      - name: Fake-Deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop == 'true' }}
        run: |
          echo "fake-deploying HCB to ${{ steps.branch-deploy.outputs.environment }}!"

      - name: Set up Ruby
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.7'
          bundler-cache: true

      - name: Deploy to ATM
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' && contains(steps.branch-deploy.outputs.environment, 'atm') }}
        env:
          MRSK_REGISTRY_USERNAME: ${{ github.actor }}
          MRSK_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          MRSK_SSH_KEY: ${{ secrets.MRSK_SSH_KEY }}
        run: |
          echo "deploying HCB to ${{ steps.branch-deploy.outputs.environment }}!"
          mkdir -p ~/.ssh/
          echo "$MRSK_SSH_KEY" > ~/.ssh/id_rsa && sudo chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ steps.branch-deploy.outputs.environment }}.hcb.gg > ~/.ssh/known_hosts
          ssh-keyscan -H warehouse.hcb.gg > ~/.ssh/known_hosts
          bundle exec mrsk deploy --destination ${{ steps.branch-deploy.outputs.environment }}

      - name: Deploy to Production
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' && steps.branch-deploy.outputs.environment == 'production' }}
        env:
          MRSK_REGISTRY_USERNAME: ${{ github.actor }}
          MRSK_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          MRSK_SSH_KEY: ${{ secrets.MRSK_SSH_KEY }}
        run: |
          echo "deploying HCB to production!"
          mkdir -p ~/.ssh/
          echo "$MRSK_SSH_KEY" > ~/.ssh/id_rsa && sudo chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H warehouse.hcb.gg > ~/.ssh/known_hosts
          ssh-keyscan -H web.hcb.gg > ~/.ssh/known_hosts
          bundle exec mrsk deploy
