name: CI
on: [push]
jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false # [ad-m/github-push-action]: otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # [ad-m/github-push-action]: otherwise, there would be errors pushing refs to the destination repository.
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.5"
          bundler-cache: true
      - name: Run Rubocop (with autocorrection)
        id: rubocop
        continue-on-error: true
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bundle exec rubocop -a
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo 'false'; else echo 'true'; fi)" >> $GITHUB_OUTPUT
      - name: Commit changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'RuboCop'
          git config --global user.email 'bank+github-rubocop-bot@hackclub.com'
          git commit -am "RuboCop autocorrect"
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GARYHTOU_GITHUB_PAT }}
          branch: ${{ github.ref }}
      - name: Fail if there were offences # Although a fix has been pushed, this commit with offences should still fail
        if: steps.git-check.outputs.modified == 'true' || steps.rubocop.outcome == 'failure'
        run: exit 1
  erblint:
    name: 'ERB Lint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.5'
          bundler-cache: true
      - name: Run erblint
        run: bundle exec erblint app/views/
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.5"
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.21.0"
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: JS package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install JS packages
        run: |
          yarn install --pure-lockfile
      - name: Install postgres client
        run: sudo apt-get install libpq-dev
      - name: Build App
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/bank_test
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bundler exec rails db:create db:migrate RAILS_ENV=test
      - name: Run RSpec
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/bank_test
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bundle exec rspec --tag ~skip
  zeitwerk:
    name: Zeitwerk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.5"
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.21.0"
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: JS package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install JS packages
        run: |
          yarn install --pure-lockfile
      - name: Run zeitwerk:check
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          RAILS_ENV: test
        run: bundle exec rails zeitwerk:check
