name: Rails tests
on: [push]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build docker-compose stack
        env:
          APP_PORT: 3000
        run: |
          docker-compose up -d
      - name: Run test
        env:
          APP_PORT: 3000
        run: |
          docker-compose exec web bundle exec rspec
