name: Rails tests
on: [push]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - name: Docker pull
        run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache || true
      - name: Docker build
        run: docker build . -t $GITHUB_REPOSITORY:${GITHUB_REF##*/} --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache
      - name: Docker setup
        env:
          APP_PORT: 3000
        run: |
          docker-compose up --detach --no-recreate
          docker-compose exec bank_web bin/rails db:setup
      - name: Run RSpec
        run: docker-compose exec bank_web bundle exec rspec
      - name: Docker push
        run: docker tag $GITHUB_REPOSITORY:${GITHUB_REF##*/} docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache || true
